export const events=[
{ type: 'jalali', month: 1, day: 1, title: 'عید نوروز' },
{ type: 'jalali', month: 1, day: 2, title: 'عید نوروز - آغاز عملیات فتح المبین (1361) – تهاجم رژیم ستم شاهی به مدرسه فیضیه قم (1342)' },
{ type: 'jalali', month: 1, day: 3, title: 'عید نورور - روز جهانی هواشناسی' },
{ type: 'jalali', month: 1, day: 4, title: 'عید نورور' },
{ type: 'jalali', month: 1, day: 6, title: 'روز امید، روز شادباش نویسی' },
{ type: 'jalali', month: 1, day: 12, title: 'روز جمهوری اسلامی ایران' },
{ type: 'jalali', month: 1, day: 13, title: 'روز طبیعت' },
{ type: 'jalali', month: 1, day: 18, title: 'روز سلامتی (روز جهانی بهداشت)' },
{ type: 'jalali', month: 1, day: 19, title: 'شهادت آیت الله سید محمد باقر صدر و خواهر ایشان بنت الهدی توسط رژیم بعث عراق (1359)' },
{ type: 'jalali', month: 1, day: 20, title: 'روز ملی فناوری هسته‌ای' },
{ type: 'jalali', month: 1, day: 21, title: 'شهادت امیر سپهبد علی صیاد شیرازی' },
{ type: 'jalali', month: 1, day: 25, title: 'روز بزرگداشت عطار نیشابوری' },
{ type: 'jalali', month: 1, day: 29, title: 'روز ارتش جمهوری اسلامی ایران' },
{ type: 'jalali', month: 1, day: 30, title: 'روز وقف' },
{ type: 'jalali', month: 2, day: 1, title: 'روز بزرگداشت سعدی' },
{ type: 'jalali', month: 2, day: 2, title: 'تاسیس سپاه پاسداران انقلاب اسلامی (1358) – سالروز انقلاب فرهنگی (1359) – روز زمین پاک' },
{ type: 'jalali', month: 2, day: 3, title: 'روز بزرگداشت شیخ بهایی' },
{ type: 'jalali', month: 2, day: 5, title: 'شکست حمله نظامی آمریکا به ایران در طبس (1359)' },
{ type: 'jalali', month: 2, day: 9, title: 'روز شوراها - ولادت حضرت معصومه (س)' },
{ type: 'jalali', month: 2, day: 10, title: 'روز ملی خلیج فارس – آغاز عملیات بیت المقدس ( 1361)' },
{ type: 'jalali', month: 2, day: 11, title: 'روز جهانی کارگر' },
{ type: 'jalali', month: 2, day: 12, title: 'شهادت استاد مطهری ( 1358) - روز معلم' },
{ type: 'jalali', month: 2, day: 15, title: 'روز بزرگداشت شیخ صدوق - روز جهانی ماما' },
{ type: 'jalali', month: 2, day: 18, title: 'روز جهانی صلیب سرخ' },
{ type: 'jalali', month: 2, day: 19, title: 'روز اسناد ملی - ولادت امام رضا' },
{ type: 'jalali', month: 2, day: 24, title: 'لغو امتیاز تنباکو به فتوای آیت الله میرزای شیرازی (1270)' },
{ type: 'jalali', month: 2, day: 25, title: 'روز بزرگداشت فردوسی' },
{ type: 'jalali', month: 2, day: 26, title: 'روز جهانی خانواده' },
{ type: 'jalali', month: 2, day: 28, title: 'روز بزرگ داشت حکیم عمر خیام – روز جهانی ارتباطات' },
{ type: 'jalali', month: 2, day: 29, title: 'روز جهانی موزه و میراث فرهنگی' },
{ type: 'jalali', month: 3, day: 1, title: 'روز بهره وری – روز بزرگداشت ملاصدرا (صدرالمتألهین) – روز جهانی توسعه فرهنگی' },
{ type: 'jalali', month: 3, day: 3, title: 'فتح خرمشهر درعملیات بیت المقدس (1361) و روز مقاومت، ایثار و پیروزی' },
{ type: 'jalali', month: 3, day: 4, title: 'روز دزفول (روز مقاومت و پایداری)' },
{ type: 'jalali', month: 3, day: 5, title: 'روز نسیم مهر (حمایت از خانواده زندانیان)' },
{ type: 'jalali', month: 3, day: 7, title: 'افتتاح اولین دوره مجلس شورای اسلامی (۱۳۵۹ هـ ش)' },
{ type: 'jalali', month: 3, day: 14, title: 'رحلت حضرت امام خمینی (ره) رهبر کبیر انقلاب و بنیانگذار جمهوری اسلامی ایران (1368) – انتخاب حضرت آیت الله خامنه ای به رهبری (1368)' },
{ type: 'jalali', month: 3, day: 15, title: 'قیام خونین 15 خرداد (1342) - روز جهانی محیط زیست - روز عرفه' },
{ type: 'jalali', month: 3, day: 20, title: 'شهادت آیت الله سعیدی توسط رژیم ستم شاهی پهوی (1349) – روز جهانی صنایع دستی' },
{ type: 'jalali', month: 3, day: 21, title: 'روز جهانی صنایع دستی' },
{ type: 'jalali', month: 3, day: 26, title: 'شهادت سربازان دلیر اسلام: بخارائی، امانی، صفار هرندی و نیک نژاد (1344)' },
{ type: 'jalali', month: 3, day: 28, title: 'روز جهانی بیابان زدایی' },
{ type: 'jalali', month: 3, day: 29, title: 'درگذشت دکتر علی شریعتی (1356)' },
{ type: 'jalali', month: 3, day: 30, title: 'شهادت زائران حرم رضوی' },
{ type: 'jalali', month: 3, day: 31, title: 'شهادت دکتر مصطفی چمران (1360) - روز بسیج استادان' },
{ type: 'jalali', month: 4, day: 1, title: 'سالروز صدور فرمان حضرت امام خمینی (ره) مبنی بر تاسیس سازمان تبلیغات اسلامی (1360) – روز اصناف' },
{ type: 'jalali', month: 4, day: 5, title: 'روز جهانی مبارزه با مواد مخدر' },
{ type: 'jalali', month: 4, day: 6, title: 'روز بزرگداشت محتشم کاشانی' },
{ type: 'jalali', month: 4, day: 7, title: 'شهادت مظلومانه آیت الله دکتر بهشتی و 72 تن از یاران امام خمینی (ره) با انفجار بمب به دست منافقین در دفتر مرکزی حزب جمهوری اسلامی (1360) – روز قوه قضاییه - روز امر به معروف و نهی از منکر - بمباران شیمیایی شهر سردشت' },
{ type: 'jalali', month: 4, day: 8, title: 'روز مبارزه با سلاح های شیمیایی و میکروبی' },
{ type: 'jalali', month: 4, day: 10, title: 'روز صنعت و معدن - بزرگداشت صائب تبریزی' },
{ type: 'jalali', month: 4, day: 11, title: 'شهادت آیت الله صدوقی چهارمین شهید محراب به دست منافقین (1361)' },
{ type: 'jalali', month: 4, day: 12, title: 'روز افشای حقوق بشر امریکایی - سقوط هواپیمای مسافربری جمهوری اسلامی ایران توسط ناوگان آمریکای جنایتکار (1367)' },
{ type: 'jalali', month: 4, day: 13, title: 'روز مبارزه با بیماری های قابل انتقال بین انسان و حیوان' },
{ type: 'jalali', month: 4, day: 14, title: 'روز قلم - روز شهرداری و دهیاری' },
{ type: 'jalali', month: 4, day: 16, title: 'روز مالیات' },
{ type: 'jalali', month: 4, day: 17, title: 'شهادت امام زین العابدین' },
{ type: 'jalali', month: 4, day: 18, title: 'روز ادبیات کودکان و نوجوانان' },
{ type: 'jalali', month: 4, day: 21, title: 'روز عفاف و حجاب' },
{ type: 'jalali', month: 4, day: 22, title: 'بزرگداشت خوارزمی' },
{ type: 'jalali', month: 4, day: 23, title: 'گشایش نخستین مجلس خبرگان رهبری (۱۳۶۲ هـ ش)' },
{ type: 'jalali', month: 4, day: 25, title: 'روز بهزیستی و تامین اجتماعی' },
{ type: 'jalali', month: 4, day: 26, title: 'تاسیس شورای نگهبان' },
{ type: 'jalali', month: 4, day: 27, title: 'اعلام پذیرش قطعنامه 598 شورای امنیت از سوی ایران (1367)' },
{ type: 'jalali', month: 4, day: 30, title: 'روز خلبان' },
{ type: 'jalali', month: 5, day: 5, title: 'سالروز عملیات غرور آفرین مرصاد (1367) - اولین نماز جمعه در سال 1358' },
{ type: 'jalali', month: 5, day: 6, title: 'روز ترویج آموزش های فنی و حرفه‌ای - ولادت امام محمد باقر' },
{ type: 'jalali', month: 5, day: 8, title: 'روز بزرگداشت شیخ شهاب الدین سهروردی ( شیخ اشراق)' },
{ type: 'jalali', month: 5, day: 9, title: 'روز اهدای خون' },
{ type: 'jalali', month: 5, day: 10, title: 'بزرگداشت سلمان فارسی' },
{ type: 'jalali', month: 5, day: 14, title: 'صدور فرمان مشروطیت (1285)' },
{ type: 'jalali', month: 5, day: 15, title: 'شهادت امیر سرلشکر خلبان عباس بابایی - انفجار بمب اتمی آمریکا در هیروشیما' },
{ type: 'jalali', month: 5, day: 16, title: 'تشکیل جهاد دانشگاهی (1359)' },
{ type: 'jalali', month: 5, day: 17, title: 'روز خبرنگار' },
{ type: 'jalali', month: 5, day: 18, title: 'بزرگداشت شهدای مدافع حرم' },
{ type: 'jalali', month: 5, day: 23, title: 'روز مقاومت اسلامی' },
{ type: 'jalali', month: 5, day: 26, title: 'آغاز بازگشت آزادگان به میهن اسلامی (1369)' },
{ type: 'jalali', month: 5, day: 28, title: 'کودتای آمریکا برای باز گرداندن شاه (1332)' },
{ type: 'jalali', month: 5, day: 29, title: 'اعلام آغاز آتش ‏بس میان ایران و عراق' },
{ type: 'jalali', month: 5, day: 30, title: 'روز بزرگداشت علامه مجلسی - روز جهانی مسجد' },
{ type: 'jalali', month: 6, day: 1, title: 'بزرگداشت ابوعلی سینا (روز پزشک)' },
{ type: 'jalali', month: 6, day: 2, title: 'آغاز هفته دولت' },
{ type: 'jalali', month: 6, day: 4, title: 'روز کارمند' },
{ type: 'jalali', month: 6, day: 5, title: 'روز داروسازی – روز بزرگداشت محمد بن زکریای رازی' },
{ type: 'jalali', month: 6, day: 8, title: 'انفجار دفتر نخست وزیری به دست منافقین و شهادت مظلومانه شهیدان رجایی و با هنر (1360) روز مبارزه با تروریسم' },
{ type: 'jalali', month: 6, day: 10, title: 'روز بانکداری اسلامی – سالروز تصویب قانون علیات بانکی بدون ریا (1362) - روز تشکیل  قرارگاه خاتم الانبیا' },
{ type: 'jalali', month: 6, day: 11, title: 'روز صنعت چاپ' },
{ type: 'jalali', month: 6, day: 12, title: 'روز بهورز' },
{ type: 'jalali', month: 6, day: 13, title: 'روز تعاون – روز بزرگداشت ابوریحان بیرونی' },
{ type: 'jalali', month: 6, day: 14, title: 'شهادت آیت الله قدوسی و سرتیپ وحید دستجردی (1360) - آغاز هفته وحدت' },
{ type: 'jalali', month: 6, day: 17, title: 'جمعه سیاه – قیام 17 شهریور و کشتار جمعی از مردم به دست ماموران ستم شاهی (1357)' },
{ type: 'jalali', month: 6, day: 19, title: 'شهادت آیت الله سید محمود طالقانی اولین امام جمعه تهران (1358)' },
{ type: 'jalali', month: 6, day: 20, title: 'شهادت دومین شهید محراب آیت الله مدنی به دست منافقین (1360)' },
{ type: 'jalali', month: 6, day: 21, title: 'روز سینما' },
{ type: 'jalali', month: 6, day: 27, title: 'روز شعر و ادب فارسی (روز بزرگداشت استاد سید محمدحسین شهریار)' },
{ type: 'jalali', month: 6, day: 30, title: 'روز گفتگوی تمدن ها' },
{ type: 'jalali', month: 6, day: 31, title: 'آغاز جنگ تحمیلی (1359) – آغاز هفته دفاع مقدس' },
{ type: 'jalali', month: 7, day: 4, title: 'روز سرباز' },
{ type: 'jalali', month: 7, day: 5, title: 'شکست حصر آبادان در عملیات ثامن الائمه (ع) (1360)' },
{ type: 'jalali', month: 7, day: 6, title: 'روز جهانی جهانگردی - روز گردشگری' },
{ type: 'jalali', month: 7, day: 7, title: 'روز آتش نشانی و ایمنی - شهادت سرداران اسلام: فلاحی، فکوری، نامجو، کلاهدوز و جهان آرا (1360)' },
{ type: 'jalali', month: 7, day: 8, title: 'روز بزرگداشت مولوی - روز جهانی دریانوردی' },
{ type: 'jalali', month: 7, day: 9, title: 'روز همبستگی و همدردی با کودکان فلسطینی – روز جهانی ناشنوایان - روز جهانی سالمندان' },
{ type: 'jalali', month: 7, day: 10, title: 'روز نخبگان' },
{ type: 'jalali', month: 7, day: 13, title: 'هجرت امام خمینی (ره) از عراق به پاریس (1357) – روز نیروی انتظامی' },
{ type: 'jalali', month: 7, day: 14, title: 'روز دامپزشکی' },
{ type: 'jalali', month: 7, day: 15, title: 'روز عملیات طوفان الاقصی - روز جهانی حماسه فلسطین' },
{ type: 'jalali', month: 7, day: 16, title: 'روز ملی کودک' },
{ type: 'jalali', month: 7, day: 17, title: 'روز جهانی پست' },
{ type: 'jalali', month: 7, day: 20, title: 'روز بزرگداشت حافظ – روز اسکن معلولین و سالمندان – روز ملی کاهش اثرات بلایای طبیعی' },
{ type: 'jalali', month: 7, day: 22, title: 'روز جهانی استاندارد' },
{ type: 'jalali', month: 7, day: 23, title: 'شهادت پنجمین شهید محراب آیت الله اشرفی اصفهانی توسط منافقین (1361) - روز جهانی نابینایان (عصای سفید)' },
{ type: 'jalali', month: 7, day: 24, title: 'روز پیوند اولیاء و مربیان' },
{ type: 'jalali', month: 7, day: 25, title: 'روز نسل کشی کودکان و زنان فلسطین' },
{ type: 'jalali', month: 7, day: 26, title: 'روز تربیت بدنی و ورزش' },
{ type: 'jalali', month: 7, day: 29, title: 'روز صادرات' },
{ type: 'jalali', month: 8, day: 1, title: 'روز آمار و برنامه ریزی' },
{ type: 'jalali', month: 8, day: 4, title: 'اعتراض و افشاگری حضرت امام خمینی (ره) علیه پذیرش کاپیتولاسیون(1343)' },
{ type: 'jalali', month: 8, day: 8, title: 'شهادت محمد حسین فهمیده ( بسیجی 13 ساله) – روز نوجوان – روز بسیج دانش آموزی' },
{ type: 'jalali', month: 8, day: 10, title: 'شهادت آیت الله قاضی طباطبایی اولین شهید محراب به دست منافقین ( 1358)' },
{ type: 'jalali', month: 8, day: 13, title: 'تبعید امام خمینی(ره) به ترکیه (13 آبان 1343) - روز دانش آموز (شهادت دانش آموزان در اعتراض به دخالت های آمریکا در ایران (13 آبان 1357)) - تسخیر لانه جاسوسی آمریکا به دست دانشجویان پیرو خط امام (13 آبان 1358) - روز ملّی مبارزه با استکبار جهانی' },
{ type: 'jalali', month: 8, day: 19, title: 'روز ملی کیفیت' },
{ type: 'jalali', month: 8, day: 24, title: 'روز کتاب و کتابخوانی – رو زبزرگدشت آیت الله علامه سید محمد حسین طباطبایی (1360)' },
{ type: 'jalali', month: 8, day: 29, title: 'روز جهانی کودک' },
{ type: 'jalali', month: 8, day: 30, title: 'روز جهانی کودک' },
{ type: 'jalali', month: 9, day: 5, title: 'روز بسیج مستضعفین، تشکیل بسج مستضعفین به فرمان امام خمینی (ره) (1358)' },
{ type: 'jalali', month: 9, day: 7, title: 'روز نیروی دریایی - شهادت شهید هسته ای محسن فخری زاده' },
{ type: 'jalali', month: 9, day: 9, title: 'روز بزرگداشت شیخ مفید' },
{ type: 'jalali', month: 9, day: 10, title: 'شهادت آیت الله سید حسن مدرس (1316) – روز مجلس' },
{ type: 'jalali', month: 9, day: 11, title: 'شهادت میرزا کوچک خان جنگلی' },
{ type: 'jalali', month: 9, day: 12, title: 'روز تصویب قانون اساسی جمهوری اسلامی ایران (1358)' },
{ type: 'jalali', month: 9, day: 13, title: 'روز بیمه – روز جهانی معلولین' },
{ type: 'jalali', month: 9, day: 16, title: 'روز دانشجو' },
{ type: 'jalali', month: 9, day: 18, title: 'معرفی عراق به عنوان مسئول و آغاز گر جنگ از سوی سازمان ملل (1370)' },
{ type: 'jalali', month: 9, day: 19, title: 'تشکیل شورای عالی انقلاب فرهنگی به فرمان امام خمینی (ره) (1363)' },
{ type: 'jalali', month: 9, day: 20, title: 'شهادت آیت الله دستغیب سومین شهید محراب به دست منافقین (1360)' },
{ type: 'jalali', month: 9, day: 25, title: 'روز پژوهش' },
{ type: 'jalali', month: 9, day: 26, title: 'روز حمل و نقل' },
{ type: 'jalali', month: 9, day: 27, title: 'شهادت آیت الله دکتر محمد مفتح (1358) – روز وحدت حوزه و دانشگاه' },
{ type: 'jalali', month: 10, day: 4, title: 'میلاد حضرت مسیح (ع)' },
{ type: 'jalali', month: 10, day: 7, title: 'شهادت آیت الله حسین غفاری توسط رژیم ستم شاهی پهلوی (1352) – سالروز تشکیل نهضت سواد آموزی به فرمان حضرت امام خمینی (ره) (1358)' },
{ type: 'jalali', month: 10, day: 9, title: 'روز بصیرت و میثاق امت با ولایت' },
{ type: 'jalali', month: 10, day: 12, title: 'آغاز سال جدید میلادی' },
{ type: 'jalali', month: 10, day: 13, title: 'روز جهانی مقاومت (سالروز شهادت سردار قاسم سلیمانی)' },
{ type: 'jalali', month: 10, day: 14, title: 'روز جهاد کشاورزی' },
{ type: 'jalali', month: 10, day: 19, title: 'قیام خونین مردم قم' },
{ type: 'jalali', month: 10, day: 20, title: 'شهادت امیر کبیر (1230 برابر با 17 ربیع الاول 1268 هجری قمری)' },
{ type: 'jalali', month: 10, day: 22, title: 'تشکیل شورای انقلاب به فرمان حضرت امام خمینی (ره) (1357)' },
{ type: 'jalali', month: 10, day: 26, title: 'فرار شاه معدوم (1357)' },
{ type: 'jalali', month: 10, day: 27, title: 'شهادت نواب صفوی، طهماسبی، برادران واحدی و ذوالقدر از فدائیان اسلام (1334)' },
{ type: 'jalali', month: 10, day: 29, title: 'روز غزه' },
{ type: 'jalali', month: 11, day: 12, title: 'بازگشت حضرت امام خمینی (ره) (1357)' },
{ type: 'jalali', month: 11, day: 14, title: 'روز فناوری فضایی' },
{ type: 'jalali', month: 11, day: 17, title: 'روز خانواده' },
{ type: 'jalali', month: 11, day: 19, title: 'روز نیروی هوایی' },
{ type: 'jalali', month: 11, day: 21, title: 'شکسته شدن حکومت نظامی به فرمان حضزت امام خمینی(ره) (1357)' },
{ type: 'jalali', month: 11, day: 22, title: 'پیروزی انقلاب اسلامی ایران و سقوط نظام شاهنشاهی (1357)' },
{ type: 'jalali', month: 11, day: 29, title: 'قیام مردم تبریز به مناسبت چهلمین روز شهادت شهدای قم' },
{ type: 'jalali', month: 12, day: 5, title: 'روز بزرگداشت خواجه نصیر الدین طوسی – روز مهندسی' },
{ type: 'jalali', month: 12, day: 8, title: 'روز امور تربیتی' },
{ type: 'jalali', month: 12, day: 9, title: 'روز ملی حمایت از حقوق مصرف کنندگان' },
{ type: 'jalali', month: 12, day: 14, title: 'روز احسان و نیکوکاری' },
{ type: 'jalali', month: 12, day: 15, title: 'روز درختکاری' },
{ type: 'jalali', month: 12, day: 20, title: 'روز راهیان نور' },
{ type: 'jalali', month: 12, day: 22, title: 'روز بزرگداشت شهدا (سالروز صدور فرمان حضرت امام خمینی (ره) مبنی بر تاسیس بنیاد شهید انقلاب اسلامی-1358)' },
{ type: 'jalali', month: 12, day: 22, title: 'روز تکریم مادران و همسران شهدا ـ روز بزرگداشت شهدا' },
{ type: 'jalali', month: 12, day: 25, title: 'بمباران شیمیایی حلبچه توسط ارتش بعث عراق (1366)' },
{ type: 'jalali', month: 12, day: 29, title: 'روز ملی شدن صنعت نفت ایران (1329)' },
{ type: 'Hijri', month: 1, day: 1, title: 'آغاز سال هجری قمری' },
{ type: 'Hijri', month: 1, day: 9, title: 'تاسوعای حسینی' },
{ type: 'Hijri', month: 1, day: 10, title: 'عاشورای حسینی - انفجار در حرم امام رضا (ع) توسط آمریکا (1415 هجری قمری) برابر با 30خرداد 1373' },
{ type: 'Hijri', month: 1, day: 11, title: 'روز تجلیل از اسرا و مفقودان' },
{ type: 'Hijri', month: 1, day: 12, title: 'شهادت امام زین العابدین (ع) (95 هجری قمری)' },
{ type: 'Hijri', month: 1, day: 18, title: 'تغییر قبله مسلمین از بیت المقدس به مکه معظمه (2 هجری قمری)' },
{ type: 'Hijri', month: 1, day: 25, title: 'شهادت امام زین العابدین (ع) (95 هجری قمری)' },
{ type: 'Hijri', month: 2, day: 7, title: 'ولادت امام موسی کاظم (ع)' },
{ type: 'Hijri', month: 2, day: 20, title: 'اربعین حسینی' },
{ type: 'Hijri', month: 2, day: 28, title: 'رحلت پیامبر اسلام (ص) (11 هجری قمری) - شهادت امام حسن مجتبی (ع) (50 هجری قمری)' },
{ type: 'Hijri', month: 2, day: 30, title: 'شهادت امام رضا (ع) (203 هجری قمری)' },
{ type: 'Hijri', month: 3, day: 1, title: 'هجرت پیامبر اسلام (ص) از مکه به مدینه ( مبدا تاریخ هجری)' },
{ type: 'Hijri', month: 3, day: 8, title: 'شهادت امام حسن عسگری (ع) (260هجری قمری)' },
{ type: 'Hijri', month: 3, day: 12, title: 'میلاد پیامبر اسلام (ص) به روایت اهل سنت – آغاز هفته وحدت' },
{ type: 'Hijri', month: 3, day: 17, title: 'ولادت پیامبر اسلام (ص) ( 53 سال قبل از هجرت) – ولادت امام جعفر صادق (ع) مؤسس مذهب جعفری (83 هجری قمری)' },
{ type: 'Hijri', month: 4, day: 8, title: 'ولادت امام حسن عسکری (ع) (232 هجری قمری)' },
{ type: 'Hijri', month: 4, day: 10, title: 'وفات حضرت معصومه (س) (201 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 1, title: 'ولادت امام محمد باقر (ع) (57 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 3, title: 'شهادت امام علی النقی الهادی (ع) (254 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 10, title: 'ولادت امام محمد تقی (ع) (جواد الائمه) (195 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 13, title: 'ولادت امیر المومنین امام علی (ع) (23 سال قبل از هجرت) - آغاز ایام البیض‌ (اعتکاف)' },
{ type: 'Hijri', month: 7, day: 15, title: 'وفات حضرت زینب (س) (62 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 25, title: 'شهادت امام موسی کاظم (ع) (183 هجری قمری)' },
{ type: 'Hijri', month: 7, day: 27, title: 'مبعث رسول مکرم اسلام (ص) (13 سال قبل از هجرت)' },
{ type: 'Hijri', month: 8, day: 3, title: 'ولادت حضرت امام حسین (ع) (4 هجری قمری) - روز پاسدار' },
{ type: 'Hijri', month: 8, day: 4, title: 'ولادت حضرت ابوالفضل (ع) (26 هجری قمری) – روز جانباز' },
{ type: 'Hijri', month: 8, day: 5, title: 'ولادت امام زین العابدین (ع) (38 هجری قمری)' },
{ type: 'Hijri', month: 8, day: 11, title: 'ولادت حضرت علی اکبر (ع) (33 هجری قمری) - روز جوان' },
{ type: 'Hijri', month: 8, day: 15, title: 'ولادت امام زمان (255 هجری قمری) و روز جهانی مستضعفان' },
{ type: 'Hijri', month: 9, day: 10, title: 'وفات حضرت خدیجه (س) (3سال قبل از هجرت)' },
{ type: 'Hijri', month: 9, day: 15, title: 'ولادت امام حسن مجتبی (ع) (3 هجری قمری)' },
{ type: 'Hijri', month: 9, day: 18, title: 'شب قدر' },
{ type: 'Hijri', month: 9, day: 19, title: 'ضربت خوردن امیر المومنین امام علی (ع) (40 هجری قمری)' },
{ type: 'Hijri', month: 9, day: 20, title: 'شب قدر' },
{ type: 'Hijri', month: 9, day: 21, title: 'شهادت امیر المومنین امام علی (ع) (40 هجری قمری)' },
{ type: 'Hijri', month: 9, day: 22, title: 'شب قدر' },
{ type: 'Hijri', month: 10, day: 1, title: 'عید سعید فطر' },
{ type: 'Hijri', month: 10, day: 8, title: 'تخریب بقیع' },
{ type: 'Hijri', month: 10, day: 21, title: 'فتح اندلس به دست مسلمانان' },
{ type: 'Hijri', month: 5, day: 8, title: 'ولادت حضرت زینب (س) (5 هجری قمری) – روز پرستار و بهورز' },
{ type: 'Hijri', month: 5, day: 13, title: ' شهادت حضرت فاطمه زهرا (س) ( 11 هجری قمری) به یک روایت' },
{ type: 'Hijri', month: 6, day: 3, title: 'شهادت حضرت فاطمه زهرا (س) (11هجری قمری)' },
{ type: 'Hijri', month: 6, day: 20, title: 'ولادت حضرت فاطمه زهرا (س) (هشتم قبل از هجزت)...– تولد امام خمینی (ره) رهبر کبیر انقلاب اسلامی(1320 هجری قمری)' },
{ type: 'Hijri', month: 11, day: 1, title: 'ولادت حضرت معصومه (س)' },
{ type: 'Hijri', month: 11, day: 11, title: 'ولادت امام رضا (ع)' },
{ type: 'Hijri', month: 11, day: 29, title: 'شهادت امام محمد تقی(ع) «جواد الائمه' },
{ type: 'Hijri', month: 12, day: 1, title: 'روز ازدواج حضرت علی (ع) و حضرت فاطمه (س) و روز ازدواج' },
{ type: 'Hijri', month: 12, day: 7, title: 'شهادت امام محمد باقر (ع)' },
{ type: 'Hijri', month: 12, day: 9, title: 'روز عرفه' },
{ type: 'Hijri', month: 12, day: 10, title: 'عید سعید قربان' },
{ type: 'Hijri', month: 12, day: 15, title: 'ولادت امام علی النقی الهادی (ع)' },
{ type: 'Hijri', month: 12, day: 18, title: 'عید سعید غدیر خم' },
{ type: 'Hijri', month: 12, day: 24, title: 'روز مباهله پیامبر با مسیحیان نجران' },
{ type: 'Hijri', month: 10, day: 25, title: 'شهادت امام جعفر صادق (ع) موسس مذهب جعفری' }
];